Jumbo frames
fsedano/kubernetes-cni-vlan pull request #1
Opened 2021-01-21 17:52 UTC by kevinpm

Changes added to /opt/cni/bin/labmon.py to support jumbo frames (just setting the mtu of the phy and veth interfaces to 9000)

2021-01-21 20:06 UTC, fsedano requested changes

2021-01-21 20:06 UTC, fsedano commented on bin/labmon_cni.py
> +        OSexec.exec(f"ip link set dev {host_if_name} mtu 9000")
Better to pass the MTU as a parameter from the deployment (as a label)

2021-02-02 13:31 UTC, kevinpm commented
Added the MTU as a label. Check if the label exists. If yes, assign the MTU value. If not, assign the default value of 1500

2021-02-03 08:25 UTC, kevinpm commented
Added UTs with annotations including the MTU

2021-02-03 12:52 UTC, fsedano commented on Dockerfile
> +COPY bin/ut_cni.py /app
I think this is already on the master branch, can you please check?

2021-02-03 12:52 UTC, fsedano commented on bin/ut_cni.py
> -    'CNI_COMMAND' : 'ADD',
Same comment - I think it's already part of the master.

2021-02-03 12:53 UTC, kevinpm commented
Closing

2021-02-03 12:53 UTC, closed without merging